name: XCS234_A2
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8.10
  - notebook=6.4.5
  - tk>=8.6.8
  - ffmpeg=4.2.2
  - moviepy=1.0.3
  - scipy=1.6.2
  - tensorboard=2.10.1
  - pyyaml=6.0
  - pip=22.1.2
  - pip:
    - matplotlib==3.5.2
    - numpy==1.23.1
    - ale-py==0.8.0
    - pyglet==1.5.26
    - gym[atari]==0.26.2
    - autorom[accept-rom-license]==0.4.2
    - cmake==3.20.5; sys_platform != "win32"
    - wget==1.0; sys_platform != "win32"
    - "--extra-index-url https://download.pytorch.org/whl/nightly/cpu"
    - torch; sys_platform != "linux" and sys_platform != "win32" and platform_machine == "arm64"
    - "--extra-index-url https://download.pytorch.org/whl/cpu"
    - torch==1.11.0; sys_platform != "linux" and sys_platform != "win32"
    - "--extra-index-url https://download.pytorch.org/whl/cpu"
    - torch==1.11.0; sys_platform == "linux" or sys_platform == "win32"
